# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feed_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feed_server.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x66\x65\x65\x64_server.proto\"\x1d\n\x0b\x46\x65\x65\x64Request\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1c\n\tFeedReply\x12\x0f\n\x07message\x18\x01 \x01(\t2*\n\x04\x66\x65\x65\x64\x12\"\n\x04Test\x12\x0c.FeedRequest\x1a\n.FeedReply\"\x00\x42\x0f\n\rkr.uwcj.cs492b\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEEDREQUEST = _descriptor.Descriptor(
  name='FeedRequest',
  full_name='FeedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='FeedRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)


_FEEDREPLY = _descriptor.Descriptor(
  name='FeedReply',
  full_name='FeedReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='FeedReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['FeedRequest'] = _FEEDREQUEST
DESCRIPTOR.message_types_by_name['FeedReply'] = _FEEDREPLY

FeedRequest = _reflection.GeneratedProtocolMessageType('FeedRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEEDREQUEST,
  __module__ = 'feed_server_pb2'
  # @@protoc_insertion_point(class_scope:FeedRequest)
  ))
_sym_db.RegisterMessage(FeedRequest)

FeedReply = _reflection.GeneratedProtocolMessageType('FeedReply', (_message.Message,), dict(
  DESCRIPTOR = _FEEDREPLY,
  __module__ = 'feed_server_pb2'
  # @@protoc_insertion_point(class_scope:FeedReply)
  ))
_sym_db.RegisterMessage(FeedReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\rkr.uwcj.cs492'))
import abc
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetafeedServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def Test(self, request, context):
    raise NotImplementedError()

class BetafeedStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def Test(self, request, timeout):
    raise NotImplementedError()
  Test.future = None

def beta_create_feed_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import feed_server_pb2
  import feed_server_pb2
  request_deserializers = {
    ('feed', 'Test'): feed_server_pb2.FeedRequest.FromString,
  }
  response_serializers = {
    ('feed', 'Test'): feed_server_pb2.FeedReply.SerializeToString,
  }
  method_implementations = {
    ('feed', 'Test'): face_utilities.unary_unary_inline(servicer.Test),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_feed_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import feed_server_pb2
  import feed_server_pb2
  request_serializers = {
    ('feed', 'Test'): feed_server_pb2.FeedRequest.SerializeToString,
  }
  response_deserializers = {
    ('feed', 'Test'): feed_server_pb2.FeedReply.FromString,
  }
  cardinalities = {
    'Test': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'feed', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
